package es.pruebas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import es.expensecalculator.web.action.GeneradorInformes;
import es.expensecalculator.web.action.TablaResultados;
import net.sf.jasperreports.engine.JRException;

public class TestInformeJasper {

	@Test
	public void test2() throws FileNotFoundException, JRException{
		GeneradorInformes generadorInformes = new GeneradorInformes();
		FileOutputStream fileOutputStream =new FileOutputStream(new File("/home/carlos/Escritorio/pp4.pdf"));
		List<TablaResultados> tablaResultados = new ArrayList<TablaResultados>();
		TablaResultados tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		List<String> eventos = new ArrayList<String>();
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		tab = new TablaResultados();
		tab.setFecha(new Date());
		tab.setSaldo(BigDecimal.ZERO);
		eventos = new ArrayList<String>();
		eventos.add("Evento 2");
//		eventos.add("Evento 2");
//		eventos.add("Evento 3");
//		eventos.add("Evento 4");
		tab.setEventos(eventos);
		tablaResultados.add(tab);
		InputStream ios = this.getClass().getResourceAsStream("/InformeSaldos.jasper");		
		generadorInformes.generarInforme(tablaResultados, fileOutputStream, ios);
	}
	
}
